package com.satoripop.rfp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CVAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAllPropertiesEquals(CV expected, CV actual) {
        assertCVAutoGeneratedPropertiesEquals(expected, actual);
        assertCVAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAllUpdatablePropertiesEquals(CV expected, CV actual) {
        assertCVUpdatableFieldsEquals(expected, actual);
        assertCVUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAutoGeneratedPropertiesEquals(CV expected, CV actual) {
        assertThat(expected)
            .as("Verify CV auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVUpdatableFieldsEquals(CV expected, CV actual) {
        assertThat(expected)
            .as("Verify CV relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVUpdatableRelationshipsEquals(CV expected, CV actual) {
        assertThat(expected)
            .as("Verify CV relationships")
            .satisfies(e -> assertThat(e.getUserConfig()).as("check userConfig").isEqualTo(actual.getUserConfig()));
    }
}
