package com.satoripop.rfp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TechnologyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnologyAllPropertiesEquals(Technology expected, Technology actual) {
        assertTechnologyAutoGeneratedPropertiesEquals(expected, actual);
        assertTechnologyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnologyAllUpdatablePropertiesEquals(Technology expected, Technology actual) {
        assertTechnologyUpdatableFieldsEquals(expected, actual);
        assertTechnologyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnologyAutoGeneratedPropertiesEquals(Technology expected, Technology actual) {
        assertThat(expected)
            .as("Verify Technology auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnologyUpdatableFieldsEquals(Technology expected, Technology actual) {
        assertThat(expected)
            .as("Verify Technology relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnologyUpdatableRelationshipsEquals(Technology expected, Technology actual) {
        assertThat(expected)
            .as("Verify Technology relationships")
            .satisfies(e -> assertThat(e.getUserConfigs()).as("check userConfigs").isEqualTo(actual.getUserConfigs()));
    }
}
